<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f7274b7a-95b4-4800-823f-2cdbcf4b5fed</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.2" />
    <PackageReference Include="Serilog.Sinks.SQLite" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="User\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockMock.Service\StockMock.Service.csproj" />
  </ItemGroup>

</Project>
